
class CustomApproachError(Exception):
    pass

class AiError(Exception):
    pass
